version: "2"

networks:
  network-health-insurance:
    name: docker_network-health-insurance
    driver: bridge

services:
  orderer.aaui.org:
    container_name: orderer.aaui.org
    image: hyperledger/fabric-orderer:2.1
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=AAUIMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:5051
      - ORDERER_GENERAL_LISTENPORT=5050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 5050:5050
      - 5051:5051
    networks:
      - network-health-insurance
    volumes:
      - ../../channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ../../organizations/ordererOrganizations/aaui.org/orderers/orderer.aaui.org/msp:/var/hyperledger/orderer/msp
      - ../../organizations/ordererOrganizations/aaui.org/orderers/orderer.aaui.org/tls:/var/hyperledger/orderer/tls

  orderer.aaji.org:
    container_name: orderer.aaji.org
    image: hyperledger/fabric-orderer:2.1
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=AAJIMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:6061
      - ORDERER_GENERAL_LISTENPORT=6050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 6050:6050
      - 6061:6061
    networks:
      - network-health-insurance
    volumes:
      - ../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../../organizations/ordererOrganizations/aaji.org/orderers/orderer.aaji.org/msp:/var/hyperledger/orderer/msp
      - ../../organizations/ordererOrganizations/aaji.org/orderers/orderer.aaji.org/tls:/var/hyperledger/orderer/tls

  peer0.prudential.co.id:
    container_name: peer0.prudential.co.id
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=PrudentialMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_network-health-insurance
      - CORE_PEER_ID=peer0.prudential.co.id
      - CORE_PEER_ADDRESS=peer0.prudential.co.id:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.prudential.co.id:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ta3.com:9051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.prudential.co.id:7051
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 7051:7051
    volumes:
      - ../../organizations/peerOrganizations/prudential.co.id/peers/peer0.prudential.co.id/msp:/etc/hyperledger/crypto/peer/msp
      - ../../organizations/peerOrganizations/prudential.co.id/peers/peer0.prudential.co.id/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      # - ./channel/:/etc/hyperledger/channel/
    networks:
      - network-health-insurance

  peer0.manulife.co.id:
    container_name: peer0.manulife.co.id
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=ManulifeMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_network-health-insurance
      - CORE_PEER_ID=peer0.manulife.co.id
      - CORE_PEER_ADDRESS=peer0.manulife.co.id:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.manulife.co.id:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manulife.co.id:8051
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 8051:8051
    volumes:
      - ../../organizations/peerOrganizations/manulife.co.id/peers/peer0.manulife.co.id/msp:/etc/hyperledger/crypto/peer/msp
      - ../../organizations/peerOrganizations/manulife.co.id/peers/peer0.manulife.co.id/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      # - ./channel/:/etc/hyperledger/channel/
    networks:
      - network-health-insurance

  peer0.allianz.co.id:
    container_name: peer0.allianz.co.id
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=AllianzMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_network-health-insurance
      - CORE_PEER_ID=peer0.allianz.co.id
      - CORE_PEER_ADDRESS=peer0.allianz.co.id:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.allianz.co.id:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ta3.com:9051
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 9051:9051
    volumes:
      - ../../organizations/peerOrganizations/allianz.co.id/peers/peer0.allianz.co.id/msp:/etc/hyperledger/crypto/peer/msp
      - ../../organizations/peerOrganizations/allianz.co.id/peers/peer0.allianz.co.id/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      # - ./channel/:/etc/hyperledger/channel/
    networks:
      - network-health-insurance
