# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  test:
    name: hospital_network

services:
  ca_sardjito:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-sardjito
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7011
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17011
    ports:
      - "7011:7011"
      - "17011:17011"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/sardjito:/etc/hyperledger/fabric-ca-server
    container_name: ca_sardjito
    networks:
      - test

  ca_dharmais:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-dharmais
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7012
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17012
    ports:
      - "7012:7012"
      - "17012:17012"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/dharmais:/etc/hyperledger/fabric-ca-server
    container_name: ca_dharmais
    networks:
      - test

  ca_arsada:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-arsada
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7010
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17010
    ports:
      - "7010:7010"
      - "17010:17010"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/arsadaOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_arsada
    networks:
      - test
